[phases.setup]
# Добавляем Bun как системный пакет
packages = ["...", "nodejs", "bun"]

[phases.install]
# Устанавливаем зависимости с помощью Bun
cmd = ["bun install"]

[phases.build]
# Собираем Next.js-приложение
cmd = ["bun run build"]

[start]
# Запускаем приложение в production-режиме
cmd = "bun run start"